# Generated by Django 2.1.4 on 2019-01-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('age', models.FloatField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('shop_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopingMall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall_name', models.CharField(max_length=50)),
                ('estd', models.IntegerField()),
                ('about', models.CharField(max_length=1000)),
                ('mall_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shoping_mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.ShopingMall'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Shop'),
        ),
    ]
