# Generated by Django 2.1.4 on 2019-01-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopingMall',
            new_name='ShoppingMall',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shoping_mall',
            new_name='shopping_mall',
        ),
    ]
